### Зарегистрировать участника
POST http://localhost:3000/v1/auth/sign-up
Content-Type: application/json

{
  "login": "iheu",
  "password": "d8578edf8458ce06fbc5bb76a58c5ca4",
  "fio": "Никита Дружинин Андреевич"
}

### Авторизация
POST http://localhost:3000/v1/auth/sign-in
Content-Type: application/json

{
  "login": "iheu",
  "password": "d8578edf8458ce06fbc5bb76a58c5ca4"
}
